version: '3.9'
services:

  aggregationapi:
    build: .
    container_name: aggregationapi
    ports:
      - '8081:8081'
    restart: always
    links:
      - redis
    depends_on:
      - backendservices
      - redis
    networks:
      - aggregation-network

  backendservices:
    image: xyzassessment/backend-services
    container_name: backendservices
    restart: always
    ports:
      - '8880:8080'
    networks:
      - aggregation-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes","--requirepass","pass"]
    expose:
      - '6379'
    networks:
      - aggregation-network

networks:
  aggregation-network:
    driver: bridge
